name: protflow
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2024.3.11=h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py311hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.51.0=py311h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - ghostscript=9.54.0=h27087fc_2
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.24.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h38be061_0
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h77fa898_7
  - libgfortran-ng=13.2.0=h69a702a_7
  - libgfortran5=13.2.0=hca663fb_7
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h77fa898_7
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hdb19cb5_3
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.3=h2797004_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hf1b16e4_1
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.8.4=py311h38be061_0
  - matplotlib-base=3.8.4=py311ha02d727_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.26.3=py311h08b1b3b_0
  - numpy-base=1.26.3=py311hf175353_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.3.0=h4ab18f5_3
  - packaging=23.2=py311h06a4308_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py311h5eee18b_0
  - pip=23.3.1=py311h06a4308_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - ply=3.11=py311h06a4308_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py311h459d7ec_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_0
  - pyqt5-sip=12.13.0=py311h5eee18b_0
  - python=3.11.7=h955ad1f_0
  - python_abi=3.11=2_cp311
  - pyzmq=25.1.2=py311h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - scipy=1.13.0=py311h08b1b3b_0
  - setuptools=68.2.2=py311h06a4308_0
  - sip=6.7.12=py311h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - tmalign=20170708=h1c9e865_6
  - tornado=6.3.3=py311h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - unicodedata2=15.1.0=py311h5eee18b_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - weblogo=3.7.9=pyhdfd78af_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - bio==1.7.0
      - biopython==1.83
      - biothings-client==0.3.1
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - gprofiler-official==1.0.0
      - idna==3.7
      - mygene==3.2.2
      - pandas==2.2.0
      - pooch==1.8.1
      - python-dateutil==2.8.2
      - pytz==2023.4
      - requests==2.32.2
      - tqdm==4.66.4
      - tzdata==2023.4
      - urllib3==2.2.1
prefix: /home/tripp/anaconda3/envs/protflow
